server:
  port: 9001
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.100.101:81

management:
  endpoint:
    web:
      exposure:
        include:'*'